# Specify all necessary information to find and connect to each hardware
# device that will be used on any of the scopes.
hardware:
  daq:
    type: synthetic
  camera:
    -
      type: synthetic
      serial_number: 302352
  filter_wheel:
    type: synthetic
    port: COM19
    baudrate: 9600
    number_of_wheels: 1
  stage:
    -
      type: synthetic
      controllername: 'C-884'
      stages: L-509.20DG10 L-509.40DG10 L-509.20DG10 M-060.DG M-406.4PD NOSTAGE
      refmode: FRF FRF FRF FRF FRF FRF
      serial_number: 119060508
    -
      type: synthetic
      serial_number: 74000375
  zoom:
    type: synthetic
    servo_id: 1
    port: COM18
    baudrate: 1000000

# Only one microscope can be active in the GUI at a time, but all microscopes will be accessible
microscopes:
  Mesoscale:
    daq:
      hardware:
        name: daq
        type: synthetic

      # NI PCIe-1073 Chassis with PXI-6259 and PXI-6733 DAQ Boards.
      # Sampling rate in Hz
      sample_rate: 100000
      sweep_time: 0.2

      # triggers
      master_trigger_out_line: PXI6259/port0/line1
      camera_trigger_out_line: /PXI6259/ctr0
      trigger_source: /PXI6259/PFI0

      # Digital Laser Outputs
      laser_port_switcher: PXI6733/port0/line0
      laser_switch_state: False

    camera:
      hardware:
        name: camera
        type: synthetic
        serial_number: 302352
      lightsheet_rolling_shutter_width: 608
      defect_correct_mode: 2.0 # Off: 1.0, On: 2.0
      delay_percent: 10
      pulse_percent: 1
      x_pixels_step: 4
      y_pixels_step: 4
      x_pixels_min: 4
      y_pixels_min: 4
      exposure_time_range:
        min: 1
        max: 1000
        step: 1
      flip_x: False
      flip_y: False
    remote_focus:
      hardware:
        name: daq
        type: synthetic
        channel: PXI6259/ao2
        min: 0
        max: 5
      # Optotune EL-16-40-TC-VIS-5D-1-C
      delay_percent: 7.5
      ramp_rising_percent: 85
      ramp_falling_percent: 2.5
      amplitude: 0.7
      offset: 2.3
      smoothing: 0.0
    galvo:
      -
        hardware:
          name: daq
          type: synthetic
          channel: PXI6259/ao0
          min: -5
          max: 5
        waveform: sine
        frequency: 99.9
        amplitude: 2.5
        offset: 0.5
        duty_cycle: 50
        phase: 1.57079 # pi/2
    filter_wheel:
      hardware:
        name: filter_wheel
        type: synthetic
        wheel_number: 1
      filter_wheel_delay: .030 # in seconds
      available_filters:
        Empty-Alignment: 0
        GFP - FF01-515/30-32: 1
        RFP - FF01-595/31-32: 2
        Far-Red - BLP01-647R/31-32: 3
        Blocked1: 4
        Blocked2: 5
        Blocked3: 6
        Blocked4: 7
        Blocked5: 8
        Blocked6: 9
    stage:
      hardware:
        -
          name: stage
          type: synthetic
          serial_number: 119060508
          axes: [x, y, z, theta, f]
          axes_mapping: [1, 2, 3, 4, 5]
          volts_per_micron: None
          axes_channels: None
          max: None
          min: None

      joystick_axes: [x, y, z]
      x_max: 100000
      x_min: -100000
      y_max: 100000
      y_min: -100000
      z_max: 100000
      z_min: -100000
      f_max: 100000
      f_min: -100000
      theta_max: 360
      theta_min: 0

      x_step: 500
      y_step: 500
      z_step: 500
      theta_step: 30
      f_step: 500
      velocity: 1000

      x_offset: 0
      y_offset: 0
      z_offset: 0
      theta_offset: 0
      f_offset: 0

      flip_x: False
      flip_y: False
      flip_z: False

    zoom:
      hardware:
        name: zoom
        type: synthetic
        servo_id: 1
      position:
        0.63x: 0
        1x: 627
        2x: 1711
        3x: 2301
        4x: 2710
        5x: 3079
        6x: 3383
      pixel_size:
        0.63x: 9.7
        1x: 6.38
        2x: 3.14
        3x: 2.12
        4x: 1.609
        5x: 1.255
        6x: 1.044
      stage_positions:
        BABB:
          f:
            0.63x: 0
            1x: 1
            2x: 2
            3x: 3
            4x: 4
            5x: 5
            6x: 6
    shutter:
      hardware:
        name: daq
        type: synthetic
        channel: PXI6259/port0/line0
        min: 0
        max: 5
    laser:
      # Omicron LightHub Ultra
      # 488 and 640 are LuxX+ Lasers
      # 561 is a Coherent OBIS Laser
      # Digital Laser Outputs
      - wavelength: 488
        onoff:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/port0/line2
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/ao0
            min: 0
            max: 5
        type: LuxX
        index: 0
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 562
        onoff:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/port0/line3
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/ao1
            min: 0
            max: 5
        type: Obis
        index: 1
        delay_percent: 10
        pulse_percent: 87
      - wavelength: 642
        onoff:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/port0/line4
            min: 0
            max: 5
        power:
          hardware:
            name: daq
            type: synthetic
            channel: PXI6733/ao2
            min: 0
            max: 5
        type: LuxX
        index: 2
        delay_percent: 10
        pulse_percent: 87

gui:
  channels:
    count: 5
    laser_power:
      min: 0
      max: 100
      step: 10
    exposure_time:
      min: 1
      max: 1000
      step: 5
    interval_time:
      min: 0
      max: 1000
      step: 5
  stack_acquisition:
    step_size:
      min: 0.100
      max: 1000
      step: 0.1
    start_pos:
      min: -5000
      max: 5000
      step: 1
    end_pos:
      min: -5000
      max: 10000
      step: 1
  timepoint:
    timepoints:
      min: 1
      max: 1000
      step: 1
    stack_pause:
      min: 0
      max: 1000
      step: 1

BDVParameters:
# The following parameters are used to configure the BigDataViewer
  # visualization. See the BigDataViewer documentation for more details.
  # https://imagej.net/BigDataViewer
  shear:
    shear_data: False
    shear_dimension: YZ # XZ, YZ, or XY
    shear_angle: 45
  rotate:
    rotate_data: False
    X: 0
    Y: 0
    Z: 0
